### PR TITLE
feat(apigateway): Add support for ApiKeys and Usage Plans

### PR DESCRIPTION
**Pull request by VED-StefanHorne**
See https://github.com/serverless-operations/serverless-apigateway-service-proxy/issues/61

### CODE REVIEW

**Comment by horike37** [comment]
Hey @VED-StefanHorne !
Thank you for adding this feature!

Can you add an explanation of it to Readme so that users can know this feature?

**Comment by VED-StefanHorne** [comment]
@horike37 done!

**Comment by sromic** [comment]
@VED-StefanHorne Thanks for this PR! I'm also waiting on this functionality fully supported by this awesome plugin :)

I might be worth considering to support serverless framework v2  and it's change to `apiKeys` definition: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#setting-api-keys-for-your-rest-api

In v2, `apiKeys` are now defined under `apiGateway` property in `providers` section.

**Comment by VED-StefanHorne** [comment]
@sromic Thanks for getting in touch! I've added you as a collaborator on my forked version so you should be able to push commits up to this PR :)

**Pull request closed without merging**
