### PR TITLE
Add support for 206 response with its relevant headers + add Accept-R…

### PR DESCRIPTION
**Pull request by michal1106**
…anges in general. prompt version to 2.2.1

### CODE REVIEW

**Comment by lopburny** [comment]
Hi @michal1106, Looks good to me 👍 
If possible, could you add simple tests for status code 206 and the headers to the file `compileMethodsToS3.test.js` ?

**Comment by michal1106** [comment]
@lopburny - good idea about the tests - it was actually causing other packages to fail and s3 test has a lot of additions
all done - please review

**Comment by lopburny** [comment]
@michal1106 I looked over the changes and they look good to me. thank you for your work👍

**Pull request merged**
