### PR TITLE
feat: allow custom response template

### PR DESCRIPTION
**Pull request by rschick**
Addresses #53

### CODE REVIEW

**Comment by horike37** [comment]
@rschick 
Thank you for opening this PR 👍 This feature looks nice!
Could you add the explanation of it to the README so that the plugin users can know how it works?

**Comment by rschick** [comment]
I updated to allow three templates, for each type of response. Let me know if you like this approach and if so I can add it for the other event sources.

**Comment by erezrokah** [comment]
@rschick very nice feature! One question - will the response always be in `application/json` or is it service dependant? Can we force it by setting an accept header?

**Comment by fahrradfahrer93** [comment]
is it possible to use this with s3? so that a POST would return the link to the resource?

**Comment by rschick** [comment]
@fahrradfahrer93 I've only implemented this for Kinesis so far. It might be possible to return the object URI, it depends what is in the response from S3.

**Comment by rschick** [comment]
Sorry I've been busy and haven't had time to work on this. I plan to address comments from @erezrokah and @fahrradfahrer93. Specifically, I will add support for the other services (S3, SQS, SNS, and DynamoDB) and provide an example of how to use values from the service response in the response template.

**Comment by satnami** [comment]
@rschick thank you for the PR, did you have any chance to continue working on it again

**Comment by rschick** [comment]
@satnami not yet, but I should have time this week to work on it.

**Comment by ffiorillosparkdigital** [comment]
Good morning! Thanks for working on this :D 
@rschick Is the idea to support custom mapping templates for other services as well? I'm specifically interested in adding custom mapping templates for **DynamoDB** proxies.

Thanks!

**Comment by ffiorillosparkdigital** [comment]
> Good morning! Thanks for working on this :D
> @rschick Is the idea to support custom mapping templates for other services as well? I'm specifically interested in adding custom mapping templates for **DynamoDB** proxies.
> 
> Thanks!

Sorry... I just saw your comment about adding support to other services. That would be awesome! :)

**Comment by balsabojic** [comment]
+1 for this feature

**Comment by gorj-tessella** [comment]
I would also like to see this implemented, particularly for S3.

**Comment by rschick** [comment]
@horike37 I haven't been able to find time to work on this. Perhaps we could merge, and allow others to contribute response template support for other integration types?

**Comment by horike37** [comment]
@rschick 

>allow others to contribute response template support for other integration types?

of course! I think you should do just what you need. Thank you for working on this 👍 
Also, the code looks good for me. merging...

**Pull request merged**
